### ISSUE TITLE
f.read() UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 836: illegal multibyte sequence

### ISSUE THREAD

**Issue by devil5967** [vsantiago113/ReadWriteMemory#1]
replace open('README.md', 'r')  to open('README.md', 'r',encoding="utf-8")

**Comment by vsantiago113** [comment]
I added the encoding, thanks for letting me know about this issue.

**Comment by vsantiago113** [comment]
I will go ahead and close this.
