### ISSUE TITLE
Can't get process from name or id

### ISSUE THREAD

**Issue by Furkan125** [vsantiago113/ReadWriteMemory#15]
Hi, i got error when try to get process from name or id

Here is my code:
from ReadWriteMemory import ReadWriteMemory
rwm = ReadWriteMemory()
process = rwm.get_process_by_name('Growtopia.exe')

But i got this error:
ReadWriteMemory.ReadWriteMemoryError: Process "" not found!

and when i try to get process from id, i got this error:
ReadWriteMemory.ReadWriteMemoryError: Process "-1" not found!

How can i fix this ? Its works fine on assault cube but i got error when i try in growtopia

**Comment by UnlightedOtaku** [comment]
You need to run python as administrator.

**Comment by Furkan125** [comment]
I run cmd as administrator and run python from cmd but i still got error. There is any other ways to run python as administrator ?

**Comment by Vincent11276** [comment]
What a coincidence! I also have the same case with Growtopia, does anyone have a solution? Running Python as administrator won't work either, it seems like Growtopia has some sort of memory manipulator prevention.

**Comment by MillhioreBT** [comment]
https://github.com/vsantiago113/ReadWriteMemory/pull/19
