### ISSUE TITLE
Process "" not found!

### ISSUE THREAD

**Issue by tank-sman** [vsantiago113/ReadWriteMemory#17]
I found something .
if be " "(space) in name of app show this error 
Example
csgo.exe --> ok    
Minecraft 1.16.4.exe --> Process "" not found!

**Comment by ErickDaGamer** [comment]
Minecraft is a Java program so the actual process name is javaw.exe

**Comment by MeblIkea** [comment]
Yes, you probably put a bad name (you should probably do what says @ErickDaCoder).

For getting your program name, go to your Task Manager (CTRL + SHIFT + ESC),
then find your program → Right click and press the properties button.
Then you should be able to find the name.

**Comment by daslikescpp** [comment]
> ###
> **[MeblIkea](/MeblIkea) ** commented [Aug 21, 2022](#issuecomment-1221395934)

I don't really get the issue here, same problem for me. When I put "-" in the process name since the process name DOES have one, it refuses to work. I used process hacker to copy the exact process name.
