### ISSUE TITLE
My* Problem reading memory! (helpme)

### ISSUE THREAD

**Issue by MillhioreBT** [vsantiago113/ReadWriteMemory#3]
Hello, how are you all? I hope well, I did not want to ask why I thought the repository was dead, but recently I saw activity and I would like to know why after some time my program stops reading the memory correctly?

I am not sure if the problem has something to do with this module, but my suspicion begins when seeing that after a while the results of reading certain parts of the memory of a program are wrong, in my case the return is 0, the problem does not have to do with the external program because I always check with the _Cheat Engine_ and the memory is still intact with its correct values

If someone wants to help me check my code, please tell me and I will give my repository permissions so they can check it out and help me detect the problem, as long as it has something to do with this module of course!

I should mention that I made some small modifications to the module in order to read text strings and some details for my convenience, so I will also leave you a link so you can see what I did directly: [__init__.py](https://ghostbin.co/paste/met7v)

If the function to read strings is correct, it could even be implemented in the module!

I am currently testing the new full access `get_all_access_handle` method to investigate if there is a possibility that an permissions refactoring was the cause, I still can't find anything regarding my problem...

Thanks!!!

**Comment by vsantiago113** [comment]
What version of the module are you using? I don't think you are using the new one based on the code you shared.

**Comment by MillhioreBT** [comment]
> What version of the module are you using? I don't think you are using the new one based on the code you shared.

I will do a couple more tests to confirm what I say, if I find that the problem is related to this module, I will let you know so that we can solve it! Thanks for replying, I thought no one would reply.

**Comment by MillhioreBT** [comment]
@vsantiago113 Hello good evening, I just found out that the last error message is number 6, do some research and find that error number 6 is when the handle is invalid.

Now my question is the following: Why is it invalid if at first it works correctly and then the handler is no longer valid? Does it have expiration or overload time?

I must emphasize that my scripts check memory many times per second, this should not be the problem from my point of view, since I have created programs in other languages ​​and I do not have this limitation, I can make all the calls I want to read the memory how many times do i want. ( Also writing as many times as it is... )

Excuse the abuse of resorting to your time, but I hope this can help you help me!! Thank!!

**Comment by vsantiago113** [comment]
On what video game are you running the code? Any chance you could share the code you are using so I can do some troubleshooting?

**Comment by vsantiago113** [comment]
I have a few questions, is this a new code you wrote or a code that was working fine and recently stopped working? Is possible you are closing the handle and it becomes invalid? Maybe the address changes causing the handle to become invalid?

**Comment by MillhioreBT** [comment]
@vsantiago113 I will give you access to the repository! Thank you for your intention to help me, I hope you don't scare my way of writing code in pyton, it is my first time with pyton, basically I am rewriting my program that I had already done in lua.

https://github.com/MillhioreBT/NecroPyBOT

**Comment by vsantiago113** [comment]
What module is the one having this issue?

**Comment by MillhioreBT** [comment]
> What module is the one having this issue?

Directly "ReadWriteMemory", what cannot be clearly identified is why it happens

**Comment by vsantiago113** [comment]
I know it is the ReadWriteMemory but I wanted to know where in your other
modules you are calling ReadWriteMemory. I want to see the your other code
so I can trace the issue all the way.

**Comment by MillhioreBT** [comment]
@vsantiago113 I couldn't manage to find the problem: V
my solution was the following:
```py
elif playerId == 0:
            Memory.loadGameClient()
            Client.updateApp()
            print("Reestablishing the connection with the client...")
            return
```
but this solution is horrible, reconnecting the handler every time the connection is lost is very cumbersome

```py
def loadGameClient():
        rwm = ReadWriteMemory()
        global PROCESS
        PROCESS = rwm.get_process_by_name(PROCESS_NAME)
        PROCESS.get_all_access_handle()
        """loadProcess es para encontrar la direccion base del proceso"""
        loadProcess()
```

**Comment by MillhioreBT** [comment]
I found the problem, when I try to read an invalid memory address, the program class *Process* breaks!
