### ISSUE TITLE
[Fix] Read/Write x64 process memory address 

### ISSUE THREAD

**Issue by jeck00119** [vsantiago113/ReadWriteMemory#5]
All you have to do is to replace :

ctypes.windll.kernel32.ReadProcessMemory(self.handle, lp_base_address, lp_buffer,n_size, lp_number_of_bytes_read)
ctypes.windll.kernel32.WriteProcessMemory(self.handle, lp_base_address, lp_buffer,n_size, lp_number_of_bytes_written)

With:

ctypes.windll.kernel32.ReadProcessMemory(self.handle, ctypes.c_void_p(lp_base_address), lp_buffer,
                                                                                                                                                              n_size, lp_number_of_bytes_read)

ctypes.windll.kernel32.WriteProcessMemory(self.handle, ctypes.c_void_p(lp_base_address), lp_buffer,
                                                                                                                                                          n_size, lp_number_of_bytes_written)

**Comment by vsantiago113** [comment]
Thanks for the solution for x64 process. I am going to test this.

**Comment by vsantiago113** [comment]
Awesome, everything works. Thanks so much!
